import LeftSidebar from "@/components/navbar/left-sidebar";
import { Box } from "@mui/material";
import React from "react";
import Header from "../../components/navbar/header";
import RightSidebar from "../../components/navbar/right-sidebar";
import { ToastContainer, toast } from "react-toastify";

// import components
import ReduxProvider from "@/libs/redux/provider";
import ReactQueryProvider from "@/libs/tanstack/provider";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
import theme from "@/theme";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import { ThemeProvider } from "@mui/material/styles";
import ProtectedPage from "@/components/guard/protected.guard";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function HomeLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <ProtectedPage/>
        <Box
          sx={{
            display: "flex",
            bgcolor: "#f0f2f5",
            minHeight: "100vh",
          }}
        >
          {/* App Bar */}
          <Header />

          {/* Mobile Drawer */}
          {/* Left Sidebar */}
          <LeftSidebar />

          {/* Main Content */}
          <Box
            component="main"
            sx={{
              flexGrow: 1,
              p: 3,
              width: { sm: `calc(100% - 480px)` },
              mt: 8,
            }}
          >
            {children}
          </Box>

          {/* Right Sidebar */}
          <RightSidebar />
        </Box>
    </>
  );
}
